const TARGET = 500;
const REPO = "simonkey888/ATM-Agent-Teller-Machine";
const OBS_ISSUE = 7;
const SAFE_KEYS = new Set(["host_class","source_sha","updated_at","controller_state","supervisor_state","supervisor_pid","phase","paused","monthly_target_usd","monthly_realized_withdrawable_usd","monthly_gap_usd","required_daily_run_rate_usd","observed_7d_run_rate_usd","observed_30d_run_rate_usd","payouts_count","human_gate_count","active_task","last_payment"]);
function headers(type){return {"content-type":type,"cache-control":"no-store","x-content-type-options":"nosniff","referrer-policy":"no-referrer"}}
function json(data,status=200){return new Response(JSON.stringify(data,null,2)+"\n",{status,headers:headers("application/json; charset=utf-8")})}
function sanitize(raw){const out={};for(const [k,v] of Object.entries(raw||{})){if(SAFE_KEYS.has(k))out[k]=v}return out}
async function liveStatus(env){
  const fallback={host_class:"UNOBSERVED",source_sha:env.ATM_GIT_SHA||"UNKNOWN",controller_state:"UNKNOWN",supervisor_state:"UNKNOWN",monthly_target_usd:String(TARGET)};
  try{
    const r=await fetch(`https://api.github.com/repos/${REPO}/issues/${OBS_ISSUE}`,{headers:{"Accept":"application/vnd.github+json","User-Agent":"atm-observatory/1"},cf:{cacheTtl:60,cacheEverything:true}});
    if(!r.ok)return fallback; const issue=await r.json(); const line=String(issue.body||"").split("\n").find(x=>x.startsWith("STATUS_JSON=")); if(!line)return fallback; return sanitize(JSON.parse(line.slice(12)));
  }catch{return fallback}
}
function esc(x){return String(x??"—").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]))}
async function page(env){const s=await liveStatus(env);const rows=[["Host",s.host_class],["Controller",s.controller_state],["Supervisor",s.supervisor_state],["Phase",s.phase],["Target USD",s.monthly_target_usd],["Realized/withdrawable USD",s.monthly_realized_withdrawable_usd],["Gap USD",s.monthly_gap_usd],["Required/day USD",s.required_daily_run_rate_usd],["7d/day USD",s.observed_7d_run_rate_usd],["30d/day USD",s.observed_30d_run_rate_usd],["Payouts",s.payouts_count],["Human gates",s.human_gate_count],["Runtime SHA",s.source_sha],["Observatory build",env.ATM_GIT_SHA||"UNKNOWN"],["Updated",s.updated_at]];const body=`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>ATM Observatory</title><style>body{font:15px ui-monospace,SFMono-Regular,Consolas,monospace;max-width:760px;margin:28px auto;padding:0 16px;line-height:1.45}h1{font-size:24px}p{overflow-wrap:anywhere}.flag{font-weight:800}.grid{display:grid;grid-template-columns:minmax(130px,1fr) minmax(0,2fr);border-top:1px solid #bbb}.grid div{padding:8px 0;border-bottom:1px solid #ddd}.v{font-weight:700;overflow-wrap:anywhere}@media(max-width:520px){.grid{grid-template-columns:1fr}.grid .v{padding-top:0}}</style></head><body><h1>ATM Observatory</h1><p class="flag">HURRY UP, TIME IS MONEY.</p><div class="grid">${rows.map(([k,v])=>`<div>${esc(k)}</div><div class="v">${esc(v)}</div>`).join("")}</div><p>Read-only sanitized state. No wallet, token, prompt, local path, or private runtime data is published.</p></body></html>`;return new Response(body,{headers:{...headers("text/html; charset=utf-8"),"content-security-policy":"default-src 'none'; style-src 'unsafe-inline'; base-uri 'none'; frame-ancestors 'none'; form-action 'none'"}})}
export default{async fetch(request,env){const u=new URL(request.url);if(!["GET","HEAD"].includes(request.method))return json({ok:false,error:"method_not_allowed"},405);if(u.pathname==="/health")return json({ok:true,service:"atm",git_sha:env.ATM_GIT_SHA||"UNKNOWN",month1_target_usd:TARGET,control_issue:4,observatory_issue:OBS_ISSUE});if(u.pathname==="/api/status")return json(await liveStatus(env));if(u.pathname==="/")return page(env);return json({ok:false,error:"not_found"},404)}};
