const TARGET = 500;
const REPO = "simonkey888/ATM-Agent-Teller-Machine";
const OBS_ISSUE = 7;
const ECONOMIC_ISSUES = [40, 39];
const OBS_MARKER = "ATM OBSERVATORY STATE";
const RADAR_MARKER = "ATM UNIVERSAL RADAR SNAPSHOT";
const ORDER013_MARKER = "ATM ORDER-013 ECONOMIC STATE";
const ORDER012_MARKER = "ATM ORDER-012 LIVE EXECUTION";
const TRUSTED_AUTHORS = new Set(["simonkey888", "github-actions[bot]"]);
const EXECUTABLE_STATE = "EXECUTABLE";
const SAFE_KEYS = new Set([
  "schema","authority","authority_epoch","cloud_heartbeat_at","runtime_sha","phase","state","paused",
  "realized_withdrawable_usd","monthly_target_usd","payouts_count","active_task","swarm","money_board",
  "last_result_status","cycle","zero_spend","cloud_run_id","payout_destinations","radar","platform_health","rail_capabilities","capability_registry","provider_registry"
]);
const SAFE_OPP = new Set(["id","source","source_object_type","url","title","category","observed_at","deadline","payout_usd","payout_net","currency","funding_status","competition","claims","submissions","open_prs","agent_policy","eligibility","executor","operational_state","money_velocity","payment_rail","withdrawal_path","source_state_hash"]);
const SAFE_PLATFORM = new Set(["source","state","checked_at","open_count","latency_ms","detail"]);
const SAFE_RAIL = new Set(["source","kind","job_counted","outgoing_spend_usd","autonomous_buying","authoritative_funding"]);
const SAFE_CAPABILITY = new Set(["capability_id","version","executor_id","checker_id","required_tools","sandbox_profile","supported_input_types","supported_output_types","cost_ceiling_usd","commercial_use_contract","benchmark_fixture_ids","benchmark_result","max_runtime_seconds","max_memory_mb","network_policy","artifact_contract","failure_policy","enabled"]);
const SAFE_PROVIDER = new Set(["provider_id","base_url","model_id","modalities","context","rate_limits","free_tier_type","commercial_use_allowed","paid_task_use_allowed","credit_card_required","auto_overage_possible","data_retention_training_disclosure","region_restrictions","last_official_verification","official_terms_url","official_pricing_url","admission","credential_present","health"]);
const SAFE_BOARD = new Set(["opportunity_value_usdc","submitted_net_usdc","accepted_net_usdc","settled_usdc","withdrawable_usdc","realized_24h_usdc","realized_30d_usdc","state","submission_id","task_id","outgoing_spend_usd","in_flight"]);
const SAFE_DESTINATION = new Set(["display_label","rail","last_30d_usd","lifetime_usd","pending_or_unsettled_usd","verification_state"]);
const PUBLIC_WALLET = "0xd89Ef03bC3105C538529AC2657Bc4488c94ff4E4";
function headers(type){return {"content-type":type,"cache-control":"no-store","x-content-type-options":"nosniff","referrer-policy":"no-referrer"}}
function json(data,status=200){return new Response(JSON.stringify(data,null,2)+"\n",{status,headers:headers("application/json; charset=utf-8")})}
function pick(raw,allow){const out={};for(const [k,v] of Object.entries(raw||{})){if(allow.has(k))out[k]=v}return out}
function trustedComment(row){if(!row||typeof row!=="object")return false;const login=String(row.user?.login||"");const association=String(row.author_association||"");return login==="github-actions[bot]"||(login==="simonkey888"&&["OWNER","MEMBER","COLLABORATOR"].includes(association))}
function sanitizeBoard(raw){const out=pick(raw||{},SAFE_BOARD);for(const key of ["opportunity_value_usdc","submitted_net_usdc","accepted_net_usdc","settled_usdc","withdrawable_usdc","realized_24h_usdc","realized_30d_usdc","outgoing_spend_usd"])out[key]=String(out[key]??"UNKNOWN");out.in_flight=Boolean(out.in_flight);return out}
function defaultDestinations(){return [{display_label:"MetaMask / Base USDC",rail:`Base USDC · ${PUBLIC_WALLET.slice(0,6)}…${PUBLIC_WALLET.slice(-4)}`,last_30d_usd:"UNKNOWN",lifetime_usd:"UNKNOWN",pending_or_unsettled_usd:"UNKNOWN",verification_state:"NO_VERIFIED_DATA"},{display_label:"Santander",rail:"BANK_PAYOUT",last_30d_usd:"UNKNOWN",lifetime_usd:"UNKNOWN",pending_or_unsettled_usd:"UNKNOWN",verification_state:"NOT_CONNECTED"}]}
function sanitizeDestinations(raw){if(!Array.isArray(raw)||!raw.length)return defaultDestinations();return raw.slice(0,8).map(x=>pick(x,SAFE_DESTINATION)).filter(x=>x.display_label&&x.verification_state)}
function sanitizeRadar(raw){
  if(!raw||typeof raw!=="object")return null;
  const rows=Array.isArray(raw.opportunities)?raw.opportunities.slice(0,60).map(x=>pick(x,SAFE_OPP)).filter(x=>x.operational_state===EXECUTABLE_STATE):[];
  const rejectionCounts=raw.rejection_counts&&typeof raw.rejection_counts==="object"?Object.fromEntries(Object.entries(raw.rejection_counts).slice(0,40).map(([k,v])=>[String(k).slice(0,60),Number(v)||0])):{};
  return {schema:String(raw.schema||"UNKNOWN"),source_sha:String(raw.source_sha||"UNKNOWN"),source_branch:String(raw.source_branch||""),generated_at:raw.generated_at||null,outgoing_spend_usd:String(raw.outgoing_spend_usd??"UNKNOWN"),source_count:Number(raw.source_count||0),scanned_count:Number(raw.scanned_count||0),opportunity_count:rows.length,current_candidates:rows.length,executable_now:rows.length,healthy_source_count:Number(raw.healthy_source_count||0),slop_rejected_last_scan:Number(raw.slop_rejected_last_scan||0),canonical_duplicate_count:Number(raw.canonical_duplicate_count||0),rejection_counts:rejectionCounts,opportunities:rows};
}
function sanitizeCapabilityRegistry(raw){const rows=Array.isArray(raw?.capabilities)?raw.capabilities.slice(0,64).map(x=>pick(x,SAFE_CAPABILITY)):[];return {schema:String(raw?.schema||"UNKNOWN"),capabilities:rows}}
function sanitizeProviderRegistry(raw){const rows=Array.isArray(raw?.providers)?raw.providers.slice(0,32).map(x=>pick(x,SAFE_PROVIDER)):[];return {schema:String(raw?.schema||"UNKNOWN"),providers:rows}}
function sanitize(raw){const out=pick(raw||{},SAFE_KEYS);if(out.money_board&&typeof out.money_board==="object")out.money_board=sanitizeBoard(out.money_board);out.payout_destinations=sanitizeDestinations(out.payout_destinations);if(out.radar&&typeof out.radar==="object")out.radar=sanitizeRadar(out.radar);if(Array.isArray(out.platform_health))out.platform_health=out.platform_health.slice(0,64).map(x=>pick(x,SAFE_PLATFORM));if(Array.isArray(out.rail_capabilities))out.rail_capabilities=out.rail_capabilities.slice(0,32).map(x=>pick(x,SAFE_RAIL));if(out.capability_registry&&typeof out.capability_registry==="object")out.capability_registry=sanitizeCapabilityRegistry(out.capability_registry);if(out.provider_registry&&typeof out.provider_registry==="object")out.provider_registry=sanitizeProviderRegistry(out.provider_registry);return out}
function fenced(body,marker){const text=String(body||"");if(!text.startsWith(marker))return null;const m=text.match(/```json\s*([\s\S]*?)\s*```/);if(!m)return null;try{return JSON.parse(m[1])}catch{return null}}
function cloudComment(row){if(!trustedComment(row))return null;const raw=fenced(row.body,OBS_MARKER);return raw?sanitize(raw):null}
function radarComment(row){if(!trustedComment(row))return null;const raw=fenced(row.body,RADAR_MARKER);if(!raw)return null;return {radar:sanitizeRadar(raw),platform_health:Array.isArray(raw.platform_health)?raw.platform_health.slice(0,64).map(x=>pick(x,SAFE_PLATFORM)):[],rail_capabilities:Array.isArray(raw.rail_capabilities)?raw.rail_capabilities.slice(0,32).map(x=>pick(x,SAFE_RAIL)):[]}}
function economicComment(row){
  if(!trustedComment(row))return null;
  let raw=fenced(row.body,ORDER013_MARKER);
  if(raw&&raw.schema==="ATM_ORDER013_ECONOMIC_STATE_V1")return sanitizeBoard(raw);
  raw=fenced(row.body,ORDER012_MARKER);
  if(raw&&raw.schema==="ATM_ORDER012_LIVE_EXECUTION_V1")return sanitizeBoard({opportunity_value_usdc:raw.net_reward_usdc,submitted_net_usdc:raw.net_reward_usdc,accepted_net_usdc:"UNKNOWN",settled_usdc:"UNKNOWN",withdrawable_usdc:"UNKNOWN",realized_24h_usdc:"0",realized_30d_usdc:"0",state:raw.state,submission_id:raw.submission_id,task_id:raw.task_id,outgoing_spend_usd:raw.outgoing_spend_usd,in_flight:raw.in_flight});
  return null;
}
async function gh(path){const r=await fetch(`https://api.github.com${path}`,{headers:{"Accept":"application/vnd.github+json","User-Agent":"atm-radar/4"},cf:{cacheTtl:20,cacheEverything:true}});if(!r.ok)throw new Error(`github_${r.status}`);return r.json()}
async function lastIssuePage(issueNumber){const issue=await gh(`/repos/${REPO}/issues/${issueNumber}`);const count=Number(issue.comments||0),page=Math.max(1,Math.ceil(count/100));return gh(`/repos/${REPO}/issues/${issueNumber}/comments?per_page=100&page=${page}`)}
async function liveMoney(){for(const issue of ECONOMIC_ISSUES){try{const comments=await lastIssuePage(issue);for(let i=comments.length-1;i>=0;i--){const state=economicComment(comments[i]);if(state)return state}}catch{}}return sanitizeBoard({state:"UNKNOWN",outgoing_spend_usd:"0",in_flight:false})}
export function deriveOperationalStatus(raw,env={},nowMs=Date.now()){
  const s=raw&&typeof raw==="object"?raw:{};
  const heartbeat=Date.parse(String(s.cloud_heartbeat_at||""));
  const cadence=Math.max(60,Math.min(300,Number(env.ATM_HEARTBEAT_CADENCE_SECONDS||300)));
  const heartbeatAge=Number.isFinite(heartbeat)?Math.max(0,Math.floor((nowMs-heartbeat)/1000)):null;
  const maxAge=Math.min(900,Math.max(180,cadence*3));
  const radar=s.radar&&typeof s.radar==="object"?s.radar:{};
  const deployed=String(env.ATM_GIT_SHA||"UNKNOWN"),radarSha=String(radar.source_sha||"UNKNOWN");
  const critical=String(s.last_result_status||"").toUpperCase();
  const checks={well_formed:Boolean(s.schema&&s.state&&s.phase),runtime_running:s.state==="RUNNING"&&!s.paused,heartbeat_fresh:heartbeatAge!==null&&heartbeatAge<=maxAge,version_coherent:/^[0-9a-f]{40}$/.test(deployed)&&radarSha===deployed,radar_current:Boolean(radar.schema==="ATM_UNIVERSAL_RADAR_PUBLIC_V3"&&radar.generated_at),source_material:Number(radar.source_count||0)>0&&Number(radar.healthy_source_count||0)>0,no_critical_fault:!/(ERROR|FAILED|CRASH|PANIC|INCOHERENT)/.test(critical)};
  const failed=Object.entries(checks).filter(([,v])=>!v).map(([k])=>k);
  let code="FAULT",label="FAULT",color="RED",reason=failed.join(",")||"unexpected_phase";
  if(!failed.length&&["CLAIM","WORK","CHECK","SUBMIT"].includes(String(s.phase||""))){code="ACTIVE";label="ACTIVE";color="GREEN";reason="fresh_active_work"}
  else if(!failed.length&&String(s.phase||"")==="DISCOVER"){code="SEARCH";label="SEARCH";color="YELLOW";reason="fresh_discovery"}
  return {code,label,color,reason,heartbeat_age_seconds:heartbeatAge,max_heartbeat_age_seconds:maxAge,checks};
}
async function liveStatus(env){
  const fallback={schema:"ATM_CLOUD_STATUS_V1",authority:"UNOBSERVED",runtime_sha:"UNKNOWN",state:"UNKNOWN",phase:"UNKNOWN",monthly_target_usd:String(TARGET),zero_spend:true,money_board:{},radar:{schema:"UNKNOWN",source_sha:"UNKNOWN",opportunities:[]},platform_health:[],rail_capabilities:[],capability_registry:{schema:"UNKNOWN",capabilities:[]},provider_registry:{schema:"UNKNOWN",providers:[]}};
  let merged=fallback;
  try{const comments=await lastIssuePage(OBS_ISSUE);let obs=null,radar=null;for(let i=comments.length-1;i>=0;i--){if(!obs)obs=cloudComment(comments[i]);if(!radar)radar=radarComment(comments[i]);if(obs&&radar)break}merged={...(obs||fallback)};if(radar){merged.radar=radar.radar;merged.platform_health=radar.platform_health;merged.rail_capabilities=radar.rail_capabilities}}catch{}
  merged.money_board=await liveMoney();merged=sanitize(merged);merged.operational_status=deriveOperationalStatus(merged,env);return merged;
}
function known(value){return value!==undefined&&value!==null&&String(value)!==""?String(value):"UNKNOWN"}
function moneyTruth(s){const b=s.money_board&&typeof s.money_board==="object"?s.money_board:{};return {opportunity_value:known(b.opportunity_value_usdc),submitted_net:known(b.submitted_net_usdc),accepted_net:known(b.accepted_net_usdc),settled_usdc:known(b.settled_usdc),withdrawable_usdc:known(b.withdrawable_usdc),realized_24h:known(b.realized_24h_usdc),realized_30d:known(b.realized_30d_usdc)}}
function esc(x){return String(x??"—").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]))}
function compact(x){if(x===undefined||x===null)return "—";if(typeof x==="object")return JSON.stringify(x);return String(x)}
function renderOpp(x){return `<article><b>${esc(x.title)}</b><div class="meta">${esc(x.source)} · ${esc(x.executor)} · ${esc(x.operational_state)} · ${esc(x.payout_net)} ${esc(x.currency)}</div><a href="${esc(x.url)}" rel="noreferrer noopener">authoritative source</a></article>`}
function renderDestination(x){return `<div class="payout-card"><b>${esc(x.display_label)}</b><div class="meta">${esc(x.rail)}</div><div>30D <strong>${esc(x.last_30d_usd)}</strong> · lifetime <strong>${esc(x.lifetime_usd)}</strong></div><div class="meta">pending ${esc(x.pending_or_unsettled_usd)} · ${esc(x.verification_state)}</div></div>`}
export function renderDashboard(s,env={}){
  const op=s.operational_status||deriveOperationalStatus(s,env),money=moneyTruth(s),radar=s.radar||{},opps=Array.isArray(radar.opportunities)?radar.opportunities.filter(x=>x.operational_state===EXECUTABLE_STATE):[];
  const healthy=Number(radar.healthy_source_count||0),sourceCount=Number(radar.source_count||0),board=s.money_board||{};
  const metrics=[["EXECUTABLE NOW",opps.length],["IN FLIGHT",board.in_flight?1:0],["SUBMITTED NET",money.submitted_net],["ACCEPTED NET",money.accepted_net],["SETTLED",money.settled_usdc],["WITHDRAWABLE",money.withdrawable_usdc],["REALIZED 24H",money.realized_24h],["REALIZED 30D",money.realized_30d],["HEALTHY SOURCES",`${healthy}/${sourceCount}`],["CURRENT CANDIDATES",Number(radar.current_candidates||opps.length)],["SLOP REJECTED",Number(radar.slop_rejected_last_scan||0)],["ZERO SPEND",s.zero_spend===true&&String(board.outgoing_spend_usd||"0")==="0"?"YES":"NO"]];
  const task=board.submission_id?`Submission ${esc(board.submission_id)} · ${esc(board.state||"UNKNOWN")}`:(s.active_task?esc(compact(s.active_task)):"No current mutation");
  const destinations=sanitizeDestinations(s.payout_destinations);
  return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>ATM Universal Money Radar</title><style>:root{color-scheme:light dark}*{box-sizing:border-box;min-width:0}body{font:14px ui-monospace,SFMono-Regular,Consolas,monospace;max-width:1040px;margin:24px auto;padding:0 14px;line-height:1.4;overflow-wrap:anywhere}h1{font-size:23px;margin:0}.title{display:flex;align-items:center;gap:10px;flex-wrap:wrap}.status-pill{border:1px solid currentColor;border-radius:999px;padding:3px 8px;font-size:12px;font-weight:800}.status-pill[data-color="GREEN"]{color:#07883d}.status-pill[data-color="YELLOW"]{color:#a06b00}.status-pill[data-color="RED"]{color:#d32727}.grid,.payout-strip{display:grid;grid-template-columns:repeat(auto-fit,minmax(155px,1fr));gap:7px;margin:18px 0}.card,article,.work,.payout-card{border:1px solid #8886;border-radius:9px;padding:10px;overflow-wrap:anywhere}.card b{display:block;font-size:17px}.meta,.diag{opacity:.72;font-size:12px}section{margin:22px 0}section h2{font-size:15px;border-bottom:1px solid #8886;padding-bottom:5px}article{margin:7px 0}a{color:inherit}.diag{border-top:1px solid #8886;padding-top:10px}@media(max-width:520px){body{margin-top:14px}.grid,.payout-strip{grid-template-columns:repeat(2,minmax(0,1fr))}}</style></head><body><div class="title"><h1>ATM Universal Money Radar</h1><span class="status-pill" data-color="${esc(op.color)}" role="status" aria-label="ATM status ${esc(op.label)}">${esc(op.label)}</span></div><p class="meta">${esc(op.reason)} · heartbeat age ${esc(op.heartbeat_age_seconds)}s</p><div class="grid">${metrics.map(([k,v])=>`<div class="card">${esc(k)}<b>${esc(v)}</b></div>`).join("")}</div><section><h2>CURRENT WORK</h2><div class="work">${task}</div></section><section><h2>PAYOUT DESTINATIONS / EARNINGS</h2><div class="payout-strip">${destinations.map(renderDestination).join("")}</div></section><section><h2>EXECUTABLE OPPORTUNITIES</h2>${opps.length?opps.map(renderOpp).join(""):"<p class=meta>None admitted by Canon.</p>"}</section><footer class="diag">runtime ${esc(String(s.runtime_sha||"UNKNOWN").slice(0,12))} · radar ${esc(String(radar.source_sha||"UNKNOWN").slice(0,12))} · deployed ${esc(String(env.ATM_GIT_SHA||"UNKNOWN").slice(0,12))} · heartbeat age ${esc(op.heartbeat_age_seconds)}s · canonical duplicates ${esc(radar.canonical_duplicate_count||0)}</footer></body></html>`;
}
async function page(env){const s=await liveStatus(env);return new Response(renderDashboard(s,env),{headers:{...headers("text/html; charset=utf-8"),"content-security-policy":"default-src 'none'; style-src 'unsafe-inline'; base-uri 'none'; frame-ancestors 'none'; form-action 'none'"}})}
function hex(bytes){return [...new Uint8Array(bytes)].map(b=>b.toString(16).padStart(2,"0")).join("")}
async function verifyCoinPay(rawBytes,signature,secret){const parts={};for(const p of String(signature||"").split(",")){const i=p.indexOf("=");if(i>0)parts[p.slice(0,i)]=p.slice(i+1)}const t=Number(parts.t),expected=String(parts.v1||"").toLowerCase();if(!Number.isInteger(t)||!/^[0-9a-f]{64}$/.test(expected))return false;if(Math.abs(Math.floor(Date.now()/1000)-t)>300)return false;const prefix=new TextEncoder().encode(`${t}.`),payload=new Uint8Array(prefix.length+rawBytes.length);payload.set(prefix,0);payload.set(rawBytes,prefix.length);const key=await crypto.subtle.importKey("raw",new TextEncoder().encode(secret),{name:"HMAC",hash:"SHA-256"},false,["sign"]);const mac=await crypto.subtle.sign("HMAC",key,payload),actual=hex(mac);let diff=actual.length^expected.length;for(let i=0;i<Math.min(actual.length,expected.length);i++)diff|=actual.charCodeAt(i)^expected.charCodeAt(i);return diff===0}
async function coinpayWebhook(request,env){if(!env.COINPAY_WEBHOOK_SECRET)return json({ok:false,error:"coinpay_disabled"},503);if(!env.ATM_RADAR_QUEUE||typeof env.ATM_RADAR_QUEUE.send!=="function")return json({ok:false,error:"queue_unavailable"},503);const rawBytes=new Uint8Array(await request.arrayBuffer());if(!(await verifyCoinPay(rawBytes,request.headers.get("x-coinpay-signature"),env.COINPAY_WEBHOOK_SECRET)))return json({ok:false,error:"invalid_signature"},401);let event;try{event=JSON.parse(new TextDecoder().decode(rawBytes))}catch{return json({ok:false,error:"invalid_json"},400)}const allowed=new Set(["payment.confirmed","payment.forwarded","escrow.settled"]);if(!allowed.has(String(event.type||"")))return json({ok:true,ignored:true},202);const data=event.data&&typeof event.data==="object"?event.data:{};const safe={id:String(event.id||""),type:String(event.type||""),created_at:String(event.created_at||""),data:{payment_id:String(data.payment_id||data.escrow_id||""),status:String(data.status||""),amount_usd:String(data.amount_usd||""),currency:String(data.currency||""),tx_hash:String(data.tx_hash||"")}};await env.ATM_RADAR_QUEUE.send(safe);return json({ok:true,queued:true},202)}
export default{async fetch(request,env){const u=new URL(request.url);if(request.method==="POST"&&u.pathname==="/webhooks/coinpay")return coinpayWebhook(request,env);if(!["GET","HEAD"].includes(request.method))return json({ok:false,error:"method_not_allowed"},405);const s=async()=>await liveStatus(env);if(u.pathname==="/health"){const state=await s();return json({ok:state.operational_status.code!=="FAULT",service:"atm",mode:"universal-money-radar",git_sha:env.ATM_GIT_SHA||"UNKNOWN",status:state.operational_status})}if(u.pathname==="/api/status")return json(await s());if(u.pathname==="/api/opportunities"){const state=await s();return json({source_sha:state.radar?.source_sha||null,generated_at:state.radar?.generated_at||null,opportunities:(state.radar?.opportunities||[]).filter(x=>x.operational_state===EXECUTABLE_STATE)})}if(u.pathname==="/api/platform-health"){const state=await s();return json({source_sha:state.radar?.source_sha||null,platforms:state.platform_health||[],rails:state.rail_capabilities||[]})}if(u.pathname==="/api/money-board"){const state=await s();return json({stages:moneyTruth(state),evidence:sanitizeBoard(state.money_board||{})})}if(u.pathname==="/api/capabilities"){const state=await s();return json(state.capability_registry||{schema:"UNKNOWN",capabilities:[]})}if(u.pathname==="/api/providers"){const state=await s();return json(state.provider_registry||{schema:"UNKNOWN",providers:[]})}if(u.pathname==="/")return page(env);return json({ok:false,error:"not_found"},404)}};
